//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL_DSW_CARRITO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDOR()
        {
            this.BOLETA = new HashSet<BOLETA>();
        }
    
        public int IDE_VEN { get; set; }
        public string NOM_VEN { get; set; }
        public string APE_VEN { get; set; }
        public string DIR_VEN { get; set; }
        public string TEL_VEN { get; set; }
        public int IDE_DIS { get; set; }
        public string COR_VEN { get; set; }
        public decimal SUE_VEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
    }
}
